name: Static Analysis
description: Run static analysis on current environment

runs:
  using: composite
  steps:
    - name: Echo banner
      shell: bash
      run: |
        echo "## Static Analysis" >> $GITHUB_STEP_SUMMARY

    - name: Analysis (Composer Defined)
      shell: bash
      run: composer analyse

#    - name: Analysis (Vendor Direct)
#      shell: bash
#      run: vendor/bin/phpstan

    - name: Echo banner
      shell: bash
      run: |
        echo "================" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
