name: Coding Style
description: Check coding style

runs:
  using: composite
  steps:
    - name: Echo banner
      shell: bash
      run: |
        echo "## Coding Style" >> $GITHUB_STEP_SUMMARY

    - name: CS check (Composer Defined)
      shell: bash
      run: composer cs-fix -- --dry-run --format=checkstyle | cs2pr

    - name: Echo banner
      shell: bash
      run: |
        echo "================" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
