name: Setup Environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment(s) to setup, besides php, e.g. mysql, etc.'
        required: true
        type: string
      php-version:
        description: 'PHP version to use'
        required: true
        type: string
      php-extensions:
        description: 'PHP extensions to install'
        required: false
        default: swoole, posix, json
        type: string
      operating-system:
        description: 'Operating system to use'
        required: true
        type: string
      use-cache:
        description: 'Use cache for composer'
        required: false
        default: true
        type: boolean

jobs:
  setup:
    runs-on: ${{ inputs.operating-system }}
    steps:
      - name: Echo banner
        run: |
          echo "Environment Info" >> $GITHUB_STEP_SUMMARY
          echo "================" >> $GITHUB_STEP_SUMMARY
          echo "OS: ${{ inputs.operating-system }}" >> $GITHUB_STEP_SUMMARY
          echo "PHP: ${{ inputs.php-version }}" >> $GITHUB_STEP_SUMMARY
          echo "Extensions: ${{ inputs.php-extensions }}" >> $GITHUB_STEP_SUMMARY
          echo "Environment: ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "Cache: ${{ inputs.use-cache }}" >> $GITHUB_STEP_SUMMARY
          echo "================" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.php-extensions }}

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        if: inputs.use-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # TODO: Setup other environments, e.g. mysql, redis, etc.
